# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_borders', '0002_usstateborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCropYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('crop_name', models.CharField(max_length=20)),
                ('region_name', models.CharField(max_length=50)),
                ('region_category', models.CharField(max_length=50)),
                ('yield_value', models.FloatField()),
                ('yield_unit', models.CharField(max_length=50)),
                ('county_code', models.IntegerField()),
                ('county_boundary_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_borders.UsCountyBorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateCropYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('crop_name', models.CharField(max_length=20)),
                ('region_name', models.CharField(max_length=50)),
                ('region_category', models.CharField(max_length=50)),
                ('yield_value', models.FloatField()),
                ('yield_unit', models.CharField(max_length=50)),
                ('state_fips_code', models.IntegerField()),
                ('state_boundary_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_borders.UsStateBorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
