# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countycropyield',
            name='state_fips_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
